name: secrets

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MY_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MY_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.MY_REGION }}
    - name: List S3 Buckets
      run: aws s3api list-buckets
